blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',  views.index, name='index'),
    path(r'posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path(r'archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path(r'categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path(r'tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path(r'search/', views.search, name='search'),
    path(r'create/',views.post_create,name='post_create')

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog.feeds import AllPostsRssFeed
from login import views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

from .settings import MEDIA_ROOT

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'index/', include('blog.urls')),
    path(r'', include('comments.urls')),
    path(r'all/rss/', AllPostsRssFeed(), name='rss'),

    path(r'login/', views.login),
    path(r'register/', views.register),
    path(r'logout/', views.logout),
    path(r'captcha/', include('captcha.urls')),  # 验证码
    path(r'profile/', views.user_profile),
    path(r'profile_edit/',views.user_edit),

    #搜索
    # 添加search的url映射
    # path('search/',include('haystack.urls')),
    # path('blog/', include("apps.news.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/models.py
from django.db import models







class User(models.Model):
    '''用户表'''

    # gender = (
    #     ('male', '男'),
    #     ('female', '女'),
    # )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    # sex = models.CharField(max_length=32, choices=gender, default='男')
    c_time = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128, unique=True)
    birth = models.CharField(max_length=100, blank=True, default="unkonwn")
    phone = models.CharField(max_length=100, blank=True)
    school = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    # upload_to 指定上传文件位置 上传头像
    # 这里指定存放在avatars/ 目录下
    avatar = models.FileField(upload_to='avatar', blank=True)
    about = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'


# class ProfileUser(models.Model):
#     name = models.CharField(max_length=128, unique=True)
#     birth = models.CharField(max_length=100, blank= True, default="konw")
#     phone = models.CharField(max_length=100, blank=True)
#     school = models.CharField(max_length=100, blank=True)
#     address = models.CharField(max_length=100, blank=True)
#     # upload_to 指定上传文件位置 上传头像
#     # 这里指定存放在avatars/ 目录下
#     about = models.TextField(blank=True)



    

login/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'input-item',
                                                                                          'placeholder': 'username'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'input-item',
                                                                                             'placeholder': 'username'}))
    # captcha = CaptchaField(label='验证码', widget=forms.TextInput(attrs={'class': 'input-item',
    #                                                                   'placeholder': '验证码'}))


class RegisterForm(forms.Form):

    
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'input-item',
                                                                                          'placeholder': 'username'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'placeholder': 'password',
                                                                                              'class': 'input-item'}))
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'comfirm your password'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control',
                                                                          'placeholder': 'e-mail'}))
  #  sex = forms.ChoiceField(label='性别', choices=gender)
    # captcha = CaptchaField(label='验证码')

    # avatar = forms.FileField(label="头像")

class UserProfileForm(forms.Form):
    avatar = forms.FileField(label="头像")
    username = forms.CharField(label="用户名", max_length=128)
    birth = forms.DateField(label='日期', widget=forms.DateInput(attrs={'type':'date'}))
    phone = forms.CharField(max_length=11)
    school = forms.CharField(max_length=100)
    address = forms.CharField(max_length=100)
    about = forms.CharField(max_length=100)
    # email = forms.CharField(max_length=20)
    # gender = (
    #     ('male', '男'),
    #     ('female', '女'),
    # )
    # sex = forms.CharField(max_length=32, choices=gender)





    

login/views.py
import hashlib,os
from blogproject.settings import MEDIA_ROOT
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import UserForm, RegisterForm, UserProfileForm
from login import models
from django.shortcuts import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url
import uuid
from PIL import Image

# def login(request):
#     # 验证码图片生成
#     hashkey = CaptchaStore.generate_key()
#     imgage_url = captcha_image_url(hashkey)
#
#
#     if request.method == "POST":
#         username = request.POST.get('username', None)
#         password = request.POST.get('password', None)
#         vcode = request.POST.get('vcode')
#         vcode_key = request.POST.get('hashkey')
#         # 验证查询数据库生成正确的码
#         get_captcha = CaptchaStore.objects.get(hashkey=vcode_key)
#
#         message = "所有字段都必须填写！"
#         if username and password:  # 确保用户名和密码都不为空
#             username = username.strip()
#             # 用户名字符合法性验证
#             # 密码长度验证
#             # 更多的其它验证.....
#             try:
#                 user = models.User.objects.get(name=username)
#                 if user.password == password:
#                     if vcode.lower() == get_captcha.response:
#                         messages.add_message(request, messages.SUCCESS, '用户登录成功！', extra_tags='success')
#                         return redirect('/index')
#                     else:
#                         return render(request, 'login/login.html', locals())
#                 else:
#                     message = "密码不正确！"
#             except:
#                 message = "用户名不存在！"
#             return render(request, 'login/login.html', locals())
#     login_form = UserForm()
#     return render(request, 'login/login.html', locals())


def login(request):
    if request.session.get('is_login', None):
        return redirect('/index')

    if request.method == "POST":
        login_form = UserForm(request.POST)
        message = "密码错误！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            try:
                user = models.User.objects.get(name=username)
                if user.password == hash_code(password):  # 哈希值和数据库内的值进行比对
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_email'] = user.email
                    request.session['user_name'] = user.name
                    request.session['user_avatar'] = str(user.avatar)


                    #  headimage = user.avatar
                    # return render(request, 'blog/index.html', locals())
                    return redirect("/index")
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'login/login.html', locals())

    login_form = UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("/index/")
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            #sex = register_form.cleaned_data['sex']
            # avatar = register_form.cleaned_data['avatar']

            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'login/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'login/register.html', locals())

                # 当一切都OK的情况下，创建新用户

                new_user = models.User.objects.create()
                new_user.name = username
                new_user.password = hash_code(password1)  # 使用加密密码
                new_user.email = email
                #new_user.sex = sex
                # new_user.avatar = avatar
                new_user.save()
                return redirect('/login/')  # 自动跳转到登录页面
    else:

        register_form = RegisterForm()
    print(register_form.errors)
    return render(request, 'login/register.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/index")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/index")


def user_profile(request):

    return render(request, "login/profile.html")


def crop_image(file, uid):
    # 随机生成新的图片名，自定义路径。
    ext = file.name.split('.')[-1]
    file_name = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    cropped_avatar = os.path.join(uid, "avatar", file_name)
    # 相对根目录路径
    if not os.path.exists(os.path.join(MEDIA_ROOT,"avatars", uid, "avatar").replace('\\','/')):
        os.makedirs(os.path.join(MEDIA_ROOT,"avatars", uid, "avatar").replace('\\','/'))
    file_path = os.path.join(MEDIA_ROOT,"avatars", uid, "avatar", file_name).replace('\\','/')
    # 裁剪图片,压缩尺寸为200*200。
    img = Image.open(file)
    crop_im = img.resize((150, 150), Image.ANTIALIAS)
    crop_im.save(file_path)

    return cropped_avatar

def delete_old_image(old_avatar,uid):
    # 物理删除图片
    tu_jpg = os.path.join(MEDIA_ROOT,"avatars",str(uid),"avatar",str(old_avatar)).replace('\\','/')
    if os.path.isfile(tu_jpg):
        os.remove(tu_jpg)


@csrf_exempt
def user_edit(request):
    if request.method == "POST":
        userprofile_form = UserProfileForm(request.POST, request.FILES)
        message = "请检查填写的内容！"

        if userprofile_form.is_valid():  # 获取数据

            ava = request.FILES.get('avatar')  # 获取上传的文件，如果没有文件，则默认为None
            # if not myFile:
            #     return HttpResponse("no files for upload!")
            # destination = open(os.path.join(MEDIA_ROOT, user_directory_path), 'wb+')  # 打开特定的文件进行二进制的写操作
            # for chunk in myFile.chunks():  # 分块写入文件
            #     destination.write(chunk)
            # destination.close()
            user1 = models.User.objects.get(id = request.session.get("user_id"))
            old_avatar = user1.avatar
            delete_old_image(old_avatar,str(request.session.get('user_id')))
            cropped_avatar= crop_image(ava, str(request.session.get('user_id'))).replace('\\','/')

            username = userprofile_form.cleaned_data['username']
            birth = userprofile_form.cleaned_data['birth']
            phone = userprofile_form.cleaned_data['phone']
            # email = userprofile_form.cleaned_data['email']
            school = userprofile_form.cleaned_data['school']
            address = userprofile_form.cleaned_data['address']
            about = userprofile_form.cleaned_data['about']


            same_name_user = models.User.objects.filter(name=username)
            if same_name_user:  # 用户名唯一
                message = '用户已经存在，请重新选择用户名！'
            # same_email_user = models.User.objects.filter(email=email)
            # if same_email_user:  # 邮箱地址唯一
            #     message = '该邮箱地址已被注册，请使用别的邮箱！'
            same_phone_user = models.User.objects.filter(phone=phone)
            if same_phone_user:  # 手机号唯一
                message = '该手机号已被注册，请使用别的手机号！'

            # 当一切都OK的情况下，保存用户信息
            edit_user = models.User.objects.get(id=request.session.get('user_id'))
            edit_user.name = username
            # edit_user.email = email
            #new_user.sex = sex
            edit_user.avatar = str(cropped_avatar)
            edit_user.about=about
            edit_user.birth=birth
            edit_user.phone=phone
            edit_user.school=school
            edit_user.address=address
            edit_user.save()

            user = models.User.objects.get(id=request.session.get('user_id'))
            request.session['user_phone'] = user.phone
            request.session['user_id'] = user.id
            request.session['user_name'] = user.name
            request.session['user_avatar'] = str(user.avatar)
            request.session['user_email'] = user.email
            request.session['user_address'] = user.address
            request.session['user_school'] = user.school
            request.session['user_about'] = user.about
            request.session['user_birth'] = user.birth



            return redirect('/profile/')  # 自动跳转到登录页面

    else:
        userprofile_form = UserProfileForm()
    print(userprofile_form.errors)
    return render(request, 'login/profile_edit.html', locals())




def hash_code(s, salt='mysite'):  # 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        * {
            margin: 0;
            padding: 0;
        }
        html {
            height: 100%;
        }
        body {
            height: 100%;
        }
        .container {
            height: 100%;
            background-image: linear-gradient(to right, #fbc2eb, #a6c1ee);
        }
        .login-wrapper {
            background-color: #fff;
            width: 358px;
            height: 588px;
            border-radius: 15px;
            padding: 0 50px;
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
        .header {
            font-size: 38px;
            font-weight: bold;
            text-align: center;
            line-height: 200px;
        }
        .input-item {
            display: block;
            width: 100%;
            margin-bottom: 20px;
            border: 0;
            padding: 10px;
            border-bottom: 1px solid rgb(128, 125, 125);
            font-size: 15px;
            outline: none;
        }
        .input-item::placeholder {
            text-transform: uppercase;
        }
        .btn {
            text-align: center;
            padding: 10px;
            width: 100%;
            margin-top: 40px;
            background-image: linear-gradient(to right, #a6c1ee, #fbc2eb);
            color: #fff;
        }
        .msg {
            text-align: center;
            line-height: 88px;
        }
        a {
            text-decoration-line: none;
            color: #abc1ee;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="login-wrapper">
            <div class="header">Login</div>
            <div class="form-wrapper">
          <form class='form-login' action="/login/" method="post">
               {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>

                <div>
                  {{ login_form.username}}
                </div>

                <div>
                    {{ login_form.password }}
                    {{ message }}

                </div>

<!--                <div class="">-->
<!--                  {{ login_form.captcha }}-->
<!--                  {{ login_form.captcha.errors }}-->
<!--                </div>-->
                <button type="submit" class="btn btn-primary pull-right">login</button>
          </form>

            <div class="msg">
                Don't have account?
                <a href="/register/">Sign up</a>
            </div>
        </div>
    </div>
</body>
</html>


<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>

     //点击刷新验证码

    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
    }
    )

</script>

templates/login/profile.html
{% load static %}
    <div class="row text-center">
    <h1>我的资料</h1>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-3 text-right">
                <span>用户名：{{ request.session.user_name }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 text-right">
                <span>出生日期：{{ request.session.user_birth }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 text-right">
                <span>联系方式：{{ request.session.user_phone }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 text-right">
                <span>邮箱：{{ request.session.user_email }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 text-right">
                <span>学校：{{ request.session.user_school }}</span>
            </div>
        </div>



        <div class="row">
            <div class="col-md-3 text-right">
                <span>地址：{{ request.session.user_address }}</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 text-right">
                <span>简介：{{ request.session.user_about }}</span>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <p>我的头像  <img width="8%" height="8%" src="/media/avatars/{{ request.session.user_avatar }}" alt="头像显示异常"></p>
    </div>
    </div>
    <div class="">
        <a href="/profile_edit/">编辑</a>
        <a href="{% url 'blog:index' %}">回到主页</a>

    </div>

templates/login/profile_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UserInfo</title>
    <style type="text/css">
        .Content-Main{
            max-width: 1200px;
            margin: auto;
            border: none;
            border-radius: 15px; 
            -moz-border-radius: 5px;
            -webkit-border-radius: 5px;
            font: 12px "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-shadow: 1px 1px 1px #444;
            color: #D3D3D3;
            background: #555;
        }
        .Content-Main h1{
            padding: 8px 0px 40px 10px;
            display: block;
            border-bottom: 1px solid #444;
        }
        .text1{
            margin-left: 3px;
        }
        .Content-Main label{
            margin: 0px 0px 5px;
            display: block;
        }
        .fileInputContainer{
            height: 99px;
            width: 99px;
            margin: 20px 20px 20px 20px ;
            border: none;
            background: url("img/Example.jpg");
            overflow: hidden; 
            position: relative; 
        }
        .fileInput{
            height: 106px;
            border: none;
            font-size: 300px;
            opacity: 0;  
            filter:alpha(opacity=0);
            cursor: pointer;
            position: absolute;
        }
        .Content-Main label>span{
            width: 20%;
            float: left;
            text-align: right;
            padding-right: 10px;
            margin-top: 10px;
            font-weight: bold;
        }
        .Main-sex{
            padding-right: 13px;
            padding-bottom: 13px;
            font-weight: bold;
            line-height: 4px; 
        }
        .Main-sex input[type=checkbox]{
            margin-top:6px;
            vertical-align:middle; 
        }
        .Content-Main input[type="text"],.Content-Main input[type="email"],.Content-Main textarea{
            height: 25px;
            width: 70%;
            line-height: 15px;
            padding: 5px 0px 5px 5px; 
            margin-bottom: 16px;
            margin-right: 6px;
            margin-top: 2px;
            border: none;
            border-radius:2px;
            -webkit-border-radius:2px;
            -moz-border-radius:2px;
            outline: 0 none; 
            background:  #DFDFDF;
            color: #525252;
        }
        .Content-Main textarea{
            height: 100px;
            width: 70%;
            padding: 5px 0px 0px 5px;
        }
        .Content-Main .button{
            padding: 8px 24px 8px 24px;
            margin-bottom: 8px;
            border: none;
            border-radius: 4px;
            -moz-border-radius: 4px;
            -webkit-border-radius: 4px;
            font-weight: bold;
            text-shadow: 1px 1px 1px #FFE477;
            box-shadow: 1px 1px 1px  #3D3D3D;
            -moz-box-shadow: 1px 1px 1px  #3D3D3D;
            -webkit-box-shadow: 1px 1px 1px  #3D3D3D;
            color: #585858;
            background: #f6ff0a;
        }
        .Content-Main .button:hover{
            color:  #333;
            background-color:  #EBEBEB ;
        }
    </style>
</head>
<body>
        <div class="Content-Main">
            <form class='form-userInfo' action="/profile_edit/" method="post" enctype="multipart/form-data">
           {% csrf_token %}

                <h1>个人信息</h1>
                <span class="text1">请在文本框中完善您的个人信息：</span>
                <p>
                <div class="fileInputContainer">
                    头像：<input  type="file" name="avatar" required id="id_avatar"></span>
                </div>








                <label>
                    <span>Your username:</span>
                    <input type="text" name="username" value="{{ request.session.user_name }}" maxlength="128" required id="id_username">
                </label>
                <!-- <label class="Main-sex">
                    <span>Your sex:</span>
                    <input type="checkbox" class="man">男
                    <input type="checkbox" class="women">女
                </label> -->
                <label>
                    <span>Your phone:</span>
                    <input type="text" name="phone" value="{{ request.session.user_phone }}"> 
                </label>
                <label>
                    <span>Your birthday:</span>
                    <input type="date" value="{{ request.session.user_birth }}" name="birth" required id="id_birth">
                </label>
                <label>
                    <span>Your school:</span>
                    <input type="text" name="school" value="{{ request.session.user_school }}" maxlength="100" required id="id_school">
                </label>
                <label>
                    <span>Your address:</span>
                    <input type="text" name="address" value="{{ request.session.user_address }}" maxlength="100" required id="id_address">
                </label>
                <label>
                    <span>About yourself::</span>
                     <input type="text" name="about" value="{{ request.session.user_about }}" maxlength="100" required id="id_about">
                </label>

                <label>
                      <input type="submit" value="确认" class="button" >
                </label>
            </form>
        </div>
</body

<script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>

    
<script>
          $(function () {
                              bindAvatar();
     });
          function bindAvatar() {
                              if(window.URL.createObjectURL){
                                        bindAvatar3();
                              }else if(window.FileReader){
                                        bindAvatar2();
                              }else {
                                        bindAvatar1();
                              }
     }
     
          /*Ajax上传至后台并返回图片的url*/
          function bindAvatar1() {
                    $("#avatarSlect").change(function () {
                    var csrf = $("input[name='csrfmiddlewaretoken']").val();
                    var formData=new FormData();
                    formData.append("csrfmiddlewaretoken",csrf);
                    formData.append('avatar', $("#avatarSlect")[0].files[0]);      /*获取上传的图片对象*/
                    $.ajax({
                              url: '/upload_avatar/',
                                                  type: 'POST',
                                                  data: formData,
                                                  contentType: false,
                                                  processData: false,
                                                  success: function (args) {
                                        console.log(args);      /*服务器端的图片地址*/
                                                                      $("#avatarPreview").attr('src','/'+args);      /*预览图片*/
                                                                      $("#avatar").val('/'+args);      /*将服务端的图片url赋值给form表单的隐藏input标签*/
                         }
                              })
     })
          }
          /*window.FileReader本地预览*/
          function bindAvatar2() {
                    console.log(2);
                                   $("#avatarSlect").change(function () {
                                                       var obj=$("#avatarSlect")[0].files[0];
                                                       var fr=new FileReader();
                                                       fr.onload=function () {
                                                                           $("#avatarPreview").attr('src',this.result);
                                                                           console.log(this.result);
                                                                           $("#avatar").val(this.result);
                              };
                              fr.readAsDataURL(obj);
                    })
     }
     /*window.URL.createObjectURL本地预览*/
     function bindAvatar3() {
               console.log(3);
                              $("#avatarSlect").change(function () {
                                                  var obj=$("#avatarSlect")[0].files[0];
                                                  var wuc=window.URL.createObjectURL(obj);
                                                       $("#avatarPreview").attr('src',wuc);
                                                       $("#avatar").val(wuc);
{#                                                   $("#avatarUrl").load(function () {#}                /*当图片加载后释放内存空间，但在jQuery3.2.1中会报错。浏览器关闭后也会自动释放*/
{#                                                                       window.URL.revokeObjectURL(wuc);#}
{#                          })#}
               })
     }
     
</script>


</html>