blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',  views.index, name='index'),
    path(r'posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path(r'archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path(r'categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path(r'tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path(r'search/', views.search, name='search'),
    path(r'create/',views.post_create,name='post_create')

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog.feeds import AllPostsRssFeed
from login import views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

from .settings import MEDIA_ROOT

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'index/', include('blog.urls')),
    path(r'', include('comments.urls')),
    path(r'all/rss/', AllPostsRssFeed(), name='rss'),

    path(r'login/', views.login),
    path(r'register/', views.register),
    path(r'logout/', views.logout),
    path(r'captcha/', include('captcha.urls')),  # 验证码
    path(r'profile/', views.user_profile),
    path(r'profile_edit/',views.user_edit),

    #搜索
    # 添加search的url映射
    # path('search/',include('haystack.urls')),
    # path('blog/', include("apps.news.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
import re

import markdown
# from django.contrib.auth.models import User
from login.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.html import strip_tags
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension




def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ]
    )
    content = md.convert(value)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    toc = m.group(1) if m is not None else ""
    return {"content": content, "toc": toc}

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    title = models.CharField('标题', max_length=70)
    body = models.TextField('正文')
    modified_time = models.DateTimeField('修改时间')
    excerpt = models.CharField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE, null=True, blank=True)
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    views = models.PositiveIntegerField(default=0, editable=False)
    picture = models.ImageField(blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)  # 覆写数据，只修改了modified_time

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    @property
    def toc(self):
        return self.rich_content.get("toc", "")

    @property
    def body_html(self):
        return self.rich_content.get("content", "")

    @cached_property
    def rich_content(self):
        return generate_rich_content(self.body)

comments/models.py
from django.db import models
from django.utils import timezone
from login.models import User


# Create your models here.
class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blog/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import Post


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Post
        # 定义表单包含的字段
        fields = ('title', 'body', 'category', 'tags', 'picture')

blog/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Category, Tag
from login.models import User
from .forms import ArticlePostForm
from django.views.generic import ListView, DetailView
from pure_pagination.mixins import PaginationMixin
from django.contrib import messages
import markdown
from django.views.decorators.csrf import csrf_exempt
import uuid,os
from PIL import Image
from blogproject.settings import MEDIA_ROOT


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    context_object_name = 'post_list'
    paginate_by = 10
    return render(request, 'blog/index.html', context={'post_list': post_list})



class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

class ArchiveView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")
        return super().get_queryset().filter(created_time__year=year, created_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        return super().get_queryset().filter(tags=t)


class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        id = kwargs['pk']
        post = Post.objects.get(id = str(id))
        pic = post.picture
        request.session['post_pic'] = str(pic)
        response = super().get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q)  )

    return render(request, 'blog/index.html', {'post_list': post_list})



def crop_image(file, pid):
    # 随机生成新的图片名，自定义路径。
    ext = file.name.split('.')[-1]
    file_name = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    cropped_avatar = os.path.join(pid, "picture", file_name)
    # 相对根目录路径

    if not os.path.exists(os.path.join(MEDIA_ROOT, "picture", pid, "picture").replace('\\', '/')):
        os.makedirs(os.path.join(MEDIA_ROOT, "picture", pid, "picture").replace('\\', '/'))
    file_path = os.path.join(MEDIA_ROOT, "picture", pid, "picture", file_name).replace('\\', '/')
    # 裁剪图片,压缩尺寸为200*200。
    img = Image.open(file)
    crop_im = img.resize((1000, 500), Image.ANTIALIAS)
    crop_im.save(file_path)

    return cropped_avatar


@csrf_exempt
def post_create(request):
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        # data=request.POST.copy()
        # author = User.objects.get(name = request.session.get('user_name'))
        # data.update({'author': author})
        # data.update({'tags': None})
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():


            title = article_post_form.cleaned_data['title']
            body = article_post_form.cleaned_data['body']
            # excerpt = article_post_form.cleaned_data['excerpt']
            category = article_post_form.cleaned_data['category']
            picture = article_post_form.cleaned_data['picture']

            tag = request.POST.get('tags')
            user__id = request.session.get('user_id')         #session get 到的只是一个属性而不是一个实例！
            author = User.objects.get(id = user__id)  #注意这里是name=user_name,而不能直接写入user_name


            pic = crop_image(picture,str(user__id))

            new_article = Post(title=title, body=body,
                               category=category,picture=str(pic),
                               author=author)
            new_article.save()
            post_id = new_article.id

            post_pic = Post.objects.get(id=post_id)
            post_pic11 = post_pic.picture
            request.session['post_picture']=str(post_pic11)

            new_article.tags.add(tag)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回文章列表
            return redirect("/index/")
        # 如果熟不不合法，返回错误信息
        else:
            print(article_post_form.errors)
            messages.add_message(request, messages.ERROR, '填写信息不完整或有误，请检查后在确认！', extra_tags='danger')
            return render(request, 'blog/create.html',locals())
        # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
    # 返回模板
    return render(request, 'blog/create.html',locals())

templates/blog/create.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Change post</title>
<link rel="stylesheet" type="text/css" href="/blogproject/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/blogproject/static/admin/css/forms.css">


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/core.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/blogproject/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/blogproject/static/admin/css/responsive.css">
<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" app-blog model-post change-form" data-admin-utc-offset="28800">
    <!-- Container -->
    <div id="container">
            <!-- Header -->
            <div id="header">
                <div id="branding">
                     <h1 id="site-name"><a href="">发表文章</a></h1>
                </div>

                <div id="user-tools">
                        Welcome
                        <strong>{{ request.session.user_name }}</strong>.
                </div>
            </div>
            <!-- END Header -->

        <div class="breadcrumbs">
        <a href="/index/">返回</a>
        </div>
            <!-- Content -->
            <div id="content" class="colM">

                <div id="content-main">


        <form action="" method="post" id="post_form"  enctype="multipart/form-data" novalidate><input type="hidden" name="csrfmiddlewaretoken" value="cbtP9xbRyzgJPwbhLWrQ7Obx1kXnSPUgIdyHbnJdk84IujfQq0BHkAmWCss8Q31z">
            <div>

              <fieldset class="module aligned ">

                    <div class="form-row field-title">
                            <div>
                                    <label class="required" for="id_title">标题:</label>
                                    <input type="text" name="title" value="" class="vTextField" maxlength="70" required id="id_title">
                            </div>
                    </div>
                    <div class="form-row field-body">
                            <div>
                                <td><label class="required" for="id_body">正文:</label></td>
                                    <ul>
                                         <td><textarea name="body" cols="40" rows="10" class="vLargeTextField" required id="id_body"></textarea></td>
                                    </ul>

                            </div>
                    </div>

                    <div class="form-row field-excerpt">
                         <td ><span style="font-size: large">上传图片<input type="file" name="picture" required id="id_picture"></span> </td>

                    </div>

                    <div class="form-row field-category">

                            <div>

                                    <label class="required" for="id_category">分类:</label>

                                        <div class="related-widget-wrapper">
                <select name="category" required id="id_category">
                    <option value="">---------</option>
                    <option value="4" selected>game</option>
                    <option value="5">study</option>
                    <option value="6">trip</option>
                    <option value="7">pet</option>
                    <option value="8">other</option>
                </select>

            </div>

                            </div>

                    </div>
                    <div class="form-row field-tags">

                            <div>
                                    <label for="id_tags">标签:</label>

                                        <div class="related-widget-wrapper">
                <select name="tags" id="id_tags" multiple>
                      <option value="12" selected>王者荣耀</option>

                      <option value="13">刺激战场</option>

                      <option value="14">修狗</option>

                      <option value="15">修猫</option>

                      <option value="16">三亚</option>



            </select>


            </div>



                                    <div class="help">Hold down "Control", or "Command" on a Mac, to select more than one.</div>

                            </div>

                    </div>

            </fieldset>













            <div class="submit-row">

            <input type="submit" value="Save" class="default" name="_save">






            </div>



                <script type="text/javascript"
                        id="django-admin-form-add-constants"
                        src="/blogproject/static/admin/js/change_form.js"
                        >
                </script>

            <script type="text/javascript"
                    id="django-admin-prepopulated-fields-constants"
                    src="/blogproject/static/admin/js/prepopulate_init.js"
                    data-prepopulated-fields="[]">
            </script>

            </div>

        </form>

            </div>

                <br class="clear">
            </div>
            <!-- END Content -->

            <div id="footer"></div>
    </div>
    <!-- END Container -->
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
     {% if request.session.is_login %}
      <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                  datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                         {{ post.body_html|safe }}
                    </div>
                    <div class="entry-content clearfix">
                          <p style="color:red">图片 <br> <img width="100%" height="50%" src="/media/picture/{{ request.session.post_pic }}" alt="图片显示异常"></p>
                    </div>

      </article>
        <section class="comment-area" id="comment-area">
            <hr>
            <h3>发表评论</h3>
            {% show_comment_form post %}
            <div class="comment-list-panel">
                {% show_comments post %}
                </div>
        </section>
        {% block toc %}
          {% if post.toc %}
            <div class="widget widget-content">
              <h3 class="widget-title">文章目录</h3>
              <div class="toc">
                <ul>
                  {{ post.toc|safe }}
                </ul>
              </div>
            </div>
          {% endif %}
        {% endblock toc %}
  {% else %}
        <h1>你尚未登录，只能访问公开内容！</h1>
    {% endif %}
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}

    {% if request.session.is_login %}
        {% for post in post_list %}
                    <article class="post post-{{ post.pk }}>
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                        datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                                <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                            </div>
                        </header>
                              <div class="entry-content clearfix">
                                  <p>{{ post.excerpt }}</p>
                                  <div class="read-more cl-effect-14">
                                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                                  </div>
                              </div>

                    </article>

                    {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                    {% endfor %}

                    {% if is_paginated %}
                        {{ page_obj.render }}
                    {% endif %}
    {% else %}
        <h1>这是一个记录网，且你尚未登录，请先登录！</h1>
    {% endif %}


    {% endblock main %}