blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',  views.index, name='index'),
    path(r'posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path(r'archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path(r'categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path(r'tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path(r'search/', views.search, name='search'),
    path(r'create/',views.post_create,name='post_create')

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog.feeds import AllPostsRssFeed
from login import views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

from .settings import MEDIA_ROOT

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'index/', include('blog.urls')),
    path(r'', include('comments.urls')),
    path(r'all/rss/', AllPostsRssFeed(), name='rss'),

    path(r'login/', views.login),
    path(r'register/', views.register),
    path(r'logout/', views.logout),
    path(r'captcha/', include('captcha.urls')),  # 验证码
    path(r'profile/', views.user_profile),
    path(r'profile_edit/',views.user_edit),

    #搜索
    # 添加search的url映射
    # path('search/',include('haystack.urls')),
    # path('blog/', include("apps.news.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load comments_extras %}
{% load blog_extras %}
<html>
<head>
    <title>learn &amp; leisure</title>
    <link rel="icon" type="image/png" sizes="64x64" href="{% static 'blog/img/logo.png' %}">

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body >
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Learn</b> &amp; Leisure</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-left">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            {% if request.session.is_login %}
                                  <li class="cl-effect-11"><a href="/profile/" data-hover="profile">profile</a></li>
                                  <li class="cl-effect-11"><a href="{% url 'blog:post_create' %}" data-hover="发文">发文</a></li>
                                  <li class="cl-effect-11"><a href="/logout/" data-hover="退出">退出</a></li>
                                  <li class="cl-effect-11" style=color:red;><a href="" data-hover="当前在线：{{ request.session.user_name }}">当前在线：{{ request.session.user_name }} </a></li>
                                  <img width="8%" height="8%" src="/media/avatars/{{ request.session.user_avatar }}" alt="头像显示异常">

                            {% else %}
                                  <li><a href="/login/">登录</a></li>
                                  <li><a href="/register/">注册</a></li>
                            {% endif %}

                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required >
                            <button type="submit" id="search"> <span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
               <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
               </main>
           <aside class="col-md-4">
              {% block toc %}
              {% endblock toc %}

              {% show_recent_posts %}
              {% show_archives %}
              {% show_categories %}
              {% show_tags %}

              <div class="rss">
                  <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>

              </div>
           </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2022 <a href=""
                                                        target="_blank" title="模板之家"></a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>